app:
  api-key:
    master: q8Qkw2Ie6YwRNUNWkGtg
  mail:
    user: dev.appscale@gmail.com
    password: ENC(rL5H8LXdbFqtFSykb8vQD9f04Oqj2gY1XSkamVXuO1Q=)
  mongodb:
    protocol: mongodb
    user: admin
    password: admin
    host: localhost:27011
    dbname: relaydb
  env:
    encrypt-password: ${ENCRYPT_PASSWORD}
  consumer:
    request-activity-log-csv-v1:
      container-config:
        group-id: activity-log-request-consumer
        idle-between-polls: 0s
      retry:
        interval: 5s
        max-attempts: 3
  constraints:
    max-activity-log-request-range: 30

logging:
  level:
    root: info

server:
  port: 8882

spring:
  application:
    name: relay-client-api
  data:
    mongodb:
      uri: ${app.mongodb.protocol}://${app.mongodb.user}:${app.mongodb.password}@${app.mongodb.host}/${app.mongodb.dbname}?authSource=admin
      auto-index-creation: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
aws:
  s3:
    bucket: dev-relay-content
    presigned-url-ttl: 1h
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    password: ${app.env.encrypt-password}
