app:
  mongodb:
    protocol: mongodb+srv
    user: prod_relay_all
    password: ENC(9uNdlY2Ff+fs48Tb4pdDRvlSSRuF/fFtGuC/N+xgyIE=)
    host: prod-relay.jyryu.mongodb.net
    dbname: relaydb

server:
  port: 8080

spring:
  data:
    mongodb:
      auto-index-creation: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
