app:
  mongodb:
    protocol: mongodb+srv
    user: prod_relay_all
    password: ENC(9uNdlY2Ff+fs48Tb4pdDRvlSSRuF/fFtGuC/N+xgyIE=)
    host: prod-relay.jyryu.mongodb.net
    dbname: relaydb

server:
  port: 8080

spring:
  data:
    mongodb:
      auto-index-creation: false
  kafka:
    producer:
      bootstrap-servers: b-1.prodrelaykafka.4g9fmo.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-2.prodrelaykafka.4g9fmo.c4.kafka.ap-northeast-2.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.amazonaws.services.schemaregistry.serializers.avro.AWSKafkaAvroSerializer
    consumer:
      bootstrap-servers: b-1.prodrelaykafka.4g9fmo.c4.kafka.ap-northeast-2.amazonaws.com:9092,b-2.prodrelaykafka.4g9fmo.c4.kafka.ap-northeast-2.amazonaws.com:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.amazonaws.services.schemaregistry.deserializers.avro.AWSKafkaAvroDeserializer
    properties:
      schema.registry.url: aws-glue-schema-registry-has-no-http-endpoint
      region: ap-northeast-2
      registry.name: prod-relay-schema-registry
      schemaAutoRegistrationEnabled: true
      compatibility: FULL
      compression: NONE
      timeToLiveMillis: 86400000
      cacheSize: 200

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
