app:
  mongodb:
    protocol: mongodb
    user: admin
    password: admin
    host: localhost:27011
    dbname: relaydb
  env:
    encrypt-password: ${ENCRYPT_PASSWORD}

logging:
  level:
    root: info

server:
  port: 8882

spring:
  application:
    name: relay-client-api
  data:
    mongodb:
      uri: ${app.mongodb.protocol}://${app.mongodb.user}:${app.mongodb.password}@${app.mongodb.host}/${app.mongodb.dbname}?authSource=admin
      auto-index-creation: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    password: ${app.env.encrypt-password}
